# Generated by Django 3.1.6 on 2021-02-18 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='state',
            field=models.CharField(default='', max_length=1024, verbose_name='State'),
            preserve_default=False,
        ),
    ]
